<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formElement($form->get('email')); ?>
                <?php if ($this->formElementErrors($form->get('email'))): ?>
                    <div class="alert alert-danger mt">
                        <?php echo $this->formElementErrors($form->get('email')); ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('password')); ?>
                <?php echo $this->formElement($form->get('password')); ?>
                <?php if ($this->formElementErrors($form->get('password'))): ?>
                    <div class="alert alert-danger mt">
                        <?php echo $this->formElementErrors($form->get('password')); ?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-group" >
                <?php echo $this->formElement($form->get('submit')); ?>
            </div>
        </form>
    </div>
</div>