<h1><?php echo $detail->getName(); ?> <small><?php echo $detail->getSubject()->getName(); ?></small></h1>

<?php foreach ($detail->getQuestions() as $number => $question): ?>
    <div class="form-group">
        <h3><?php echo ($number + 1); ?>.- <?php echo $question->getName(); ?></h3>
        <?php foreach ($question->getAnswers() as $answer): ?>
            <p class="bg-danger p"><?php echo $answer->getText(); ?></p>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>
