<div class="row">
    <div class="row">
        <div class="col-md-8">
            <h1><?php echo $parent->getName(); ?></h1>
        </div>
        <div class="col-md-4">
            <a href="<?php echo $this->url('answer', ['action' => 'new', 'id' => $parent->getId()]); ?>" class="btn btn-primary btn-sm">New</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <th>#</th>
                    <th>Answer</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    <?php foreach ($results as $answer): ?>
                        <tr>
                            <td><?php echo $answer->getId(); ?></td>
                            <td><?php echo $answer->getText(); ?></td>
                            <td>
                                <a href="<?php echo $this->url('answer', ['action' => 'edit', 'id' => $answer->getId()]); ?>" class="btn btn-warning btn-xs">Edit</a>
                                <a href="<?php echo $this->url('answer', ['action' => 'delete', 'id' => $answer->getId()]); ?>" class="btn btn-danger btn-xs">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
