<div class="row">
    <div class="row">
        <div class="col-md-12">
            <a href="<?php echo $this->url('subject', ['action' => 'new']); ?>" class="btn btn-primary btn-sm pull-left">New</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <th>#</th>
                    <th>Subject</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    <?php foreach ($results as $subject): ?>
                        <tr>
                            <td><?php echo $subject->getId(); ?></td>
                            <td><?php echo $subject->getName(); ?></td>
                            <td>
                                <a href="<?php echo $this->url('subject', ['action' => 'edit', 'id' => $subject->getId()]); ?>" class="btn btn-warning btn-xs">Edit</a>
                                <a href="<?php echo $this->url('subject', ['action' => 'delete', 'id' => $subject->getId()]); ?>" class="btn btn-danger btn-xs">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
