<div class="row">
    <div class="row">
        <div class="col-md-12">
            <a href="<?php echo $this->url('question', ['action' => 'new']); ?>" class="btn btn-primary btn-sm pull-left">New</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <th>#</th>
                    <th>Question</th>
                    <th>Answers</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    <?php foreach ($results as $question): ?>
                        <tr>
                            <td><?php echo $question->getId(); ?></td>
                            <td><?php echo $question->getName(); ?></td>
                            <td><?php echo $question->getAnswers()->count(); ?></td>
                            <td>
                                <a href="<?php echo $this->url('answer', ['action' => 'index', 'id' => $question->getId()]); ?>" class="btn btn-info btn-xs">Answers</a>
                                <a href="<?php echo $this->url('question', ['action' => 'edit', 'id' => $question->getId()]); ?>" class="btn btn-warning btn-xs">Edit</a>
                                <a href="<?php echo $this->url('question', ['action' => 'delete', 'id' => $question->getId()]); ?>" class="btn btn-danger btn-xs">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
